ARG AGENT=opencode
FROM ghcr.io/mattolson/agent-sandbox-${AGENT}

USER root
RUN /etc/agent-sandbox/stacks/go.sh 1.26.1

ENV GOPATH=/home/dev/go
ENV PATH=/usr/local/go/bin:/home/dev/go/bin:$PATH

USER dev
