#!/bin/bash
set -euo pipefail

# Refresh managed image digests, then pin the agent CLI versions those images
# carry so the local dev image rebuild actually reinstalls them.
#
# `agentbox bump` only repins digests in the managed compose layers. This repo
# overrides the agent image with a locally built agent-sandbox-dev:<agent>, so
# those digests are never pulled at run time. The versions the bumped images
# were built with are still the right thing to build locally, and they are
# recorded as image labels, so read them back and write them to the versions
# file that build-dev-image.bash applies.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
COMPOSE_DIR="${COMPOSE_DIR:-$REPO_ROOT/.agent-sandbox/compose}"
VERSIONS_FILE="${VERSIONS_FILE:-$SCRIPT_DIR/dev-image-versions.env}"

SUPPORTED_AGENTS="claude copilot codex gemini factory opencode pi hermes"

usage() {
	cat <<'EOF'
Usage: ./scripts/bump-dev-image.bash

Runs `agentbox bump` to refresh managed image digests, then reads the agent CLI
version label off each newly pinned image and records it in the versions file
consumed by ./scripts/build-dev-image.bash.

Does not rebuild anything. Use `make bump` to bump and then run `make setup`.

Optional environment variables:
  AGENTBOX       agentbox command to run (default: agentbox on PATH,
                 then ./bin/agentbox, then `go run ./cmd/agentbox`)
  COMPOSE_DIR    Managed compose directory (default: ./.agent-sandbox/compose)
  VERSIONS_FILE  Output file (default: ./scripts/dev-image-versions.env)
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
	usage
	exit 0
fi

# build.sh environment variable that sets this agent's CLI version.
version_var_for() {
	case "$1" in
		claude) printf 'CLAUDE_CODE_VERSION' ;;
		copilot) printf 'COPILOT_VERSION' ;;
		codex) printf 'CODEX_VERSION' ;;
		gemini) printf 'GEMINI_VERSION' ;;
		factory) printf 'FACTORY_VERSION' ;;
		opencode) printf 'OPENCODE_VERSION' ;;
		pi) printf 'PI_VERSION' ;;
		hermes) printf 'HERMES_VERSION' ;;
		*) return 1 ;;
	esac
}

# Image label holding the value that the above variable expects. Hermes is the
# odd one: HERMES_VERSION is a git tag, which is recorded as hermes-ref, while
# hermes-version holds the derived semver.
version_label_for() {
	case "$1" in
		claude) printf 'com.mattolson.agentsandbox.claude-code-version' ;;
		copilot) printf 'com.mattolson.agentsandbox.copilot-version' ;;
		codex) printf 'com.mattolson.agentsandbox.codex-version' ;;
		gemini) printf 'com.mattolson.agentsandbox.gemini-version' ;;
		factory) printf 'com.mattolson.agentsandbox.factory-version' ;;
		opencode) printf 'com.mattolson.agentsandbox.opencode-version' ;;
		pi) printf 'com.mattolson.agentsandbox.pi-version' ;;
		hermes) printf 'com.mattolson.agentsandbox.hermes-ref' ;;
		*) return 1 ;;
	esac
}

# Mirrors docker.IsLocalImageRef in internal/docker/images.go.
is_local_image() {
	case "$1" in
		*:local) return 0 ;;
		*/*) return 1 ;;
		*) return 0 ;;
	esac
}

# Reads the `image:` value from the `agent` service of a managed compose layer.
# These files are generated by internal/scaffold, so the indentation is stable.
read_agent_image() {
	awk '
		/^[[:space:]]*services:[[:space:]]*$/ { in_services = 1; next }
		in_services && /^  [A-Za-z0-9_.-]+:[[:space:]]*$/ {
			svc = $0
			sub(/^  /, "", svc)
			sub(/:[[:space:]]*$/, "", svc)
			next
		}
		svc == "agent" && /^    image:[[:space:]]*/ {
			sub(/^    image:[[:space:]]*/, "")
			print
			exit
		}
	' "$1"
}

read_pinned_version() {
	# $1 = variable name
	[ -f "$VERSIONS_FILE" ] || return 0
	sed -n "s/^$1=//p" "$VERSIONS_FILE" | tail -1
}

if ! command -v docker >/dev/null 2>&1; then
	printf 'docker is required to read version labels from bumped images\n' >&2
	exit 1
fi

if [ ! -d "$COMPOSE_DIR" ]; then
	printf 'Managed compose directory not found: %s\nRun `agentbox init` first.\n' "$COMPOSE_DIR" >&2
	exit 1
fi

cd "$REPO_ROOT"

AGENTBOX_CMD=()
if [ -n "${AGENTBOX:-}" ]; then
	# Word splitting is intentional so AGENTBOX can carry arguments.
	# shellcheck disable=SC2206
	AGENTBOX_CMD=($AGENTBOX)
elif command -v agentbox >/dev/null 2>&1; then
	AGENTBOX_CMD=(agentbox)
elif [ -x "$REPO_ROOT/bin/agentbox" ]; then
	AGENTBOX_CMD=("$REPO_ROOT/bin/agentbox")
elif command -v go >/dev/null 2>&1; then
	AGENTBOX_CMD=(go run ./cmd/agentbox)
else
	printf 'Unable to locate agentbox. Install it, run `make build`, or set AGENTBOX.\n' >&2
	exit 1
fi

printf 'Running %s bump\n' "${AGENTBOX_CMD[*]}"
"${AGENTBOX_CMD[@]}" bump

printf '\nReading agent CLI versions from bumped images\n'

RESOLVED_FILE="$(mktemp)"
trap 'rm -f "$RESOLVED_FILE"' EXIT

for agent in $SUPPORTED_AGENTS; do
	layer="$COMPOSE_DIR/agent.$agent.yml"
	[ -f "$layer" ] || continue

	image="$(read_agent_image "$layer")"
	if [ -z "$image" ]; then
		printf '  %s: no agent image in %s, skipping\n' "$agent" "$layer" >&2
		continue
	fi

	if is_local_image "$image"; then
		printf '  %s: %s is a local image, skipping\n' "$agent" "$image" >&2
		continue
	fi

	label="$(version_label_for "$agent")"
	version="$(docker image inspect --format "{{ index .Config.Labels \"$label\" }}" "$image" 2>/dev/null || printf '')"
	version="$(printf '%s' "$version" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

	case "$version" in
		'')
			printf '  %s: no %s label on %s, skipping\n' "$agent" "$label" "$image" >&2
			continue
			;;
		latest)
			printf '  %s: image was built from "latest" and carries no concrete version, skipping\n' "$agent" >&2
			continue
			;;
		# Catches Go template misses like "<no value>" and any other junk that
		# would be unsafe to write into a KEY=value file or pass to build.sh.
		*[!A-Za-z0-9._+-]*)
			printf '  %s: unexpected %s label value "%s", skipping\n' "$agent" "$label" "$version" >&2
			continue
			;;
	esac

	printf '  %s: %s\n' "$agent" "$version"
	printf '%s %s\n' "$agent" "$version" >> "$RESOLVED_FILE"
done

if [ ! -s "$RESOLVED_FILE" ]; then
	printf '\nNo agent versions resolved. Leaving %s unchanged.\n' "$VERSIONS_FILE" >&2
	exit 0
fi

TMP_VERSIONS="$(mktemp)"
trap 'rm -f "$RESOLVED_FILE" "$TMP_VERSIONS"' EXIT

cat <<'EOF' > "$TMP_VERSIONS"
# Agent CLI versions pinned for the local dev image.
#
# Generated by ./scripts/bump-dev-image.bash (via `make bump`) and read by
# ./scripts/build-dev-image.bash (via `make setup`).
#
# Each entry is applied as a default: an explicit environment variable always
# wins, so `CLAUDE_CODE_VERSION=2.1.100 make setup` still overrides a pin here.
#
# Pinning matters because images/build.sh defaults these to "latest", which is a
# cache-stable build arg. Docker reuses the cached install layer and the agent
# CLI never gets reinstalled. A concrete version busts the cache.
EOF

changed=0
for agent in $SUPPORTED_AGENTS; do
	var="$(version_var_for "$agent")"
	previous="$(read_pinned_version "$var")"
	version="$(awk -v a="$agent" '$1 == a { print $2; exit }' "$RESOLVED_FILE")"

	# Carry forward pins for agents that were not resolved this run.
	if [ -z "$version" ]; then
		version="$previous"
	elif [ "$version" != "$previous" ]; then
		changed=1
		if [ -n "$previous" ]; then
			printf '  %s: %s -> %s\n' "$var" "$previous" "$version"
		else
			printf '  %s: pinned to %s\n' "$var" "$version"
		fi
	fi

	[ -n "$version" ] || continue
	printf '%s=%s\n' "$var" "$version" >> "$TMP_VERSIONS"
done

mv "$TMP_VERSIONS" "$VERSIONS_FILE"
trap 'rm -f "$RESOLVED_FILE"' EXIT

if [ "$changed" -eq 0 ]; then
	printf '\nNo version changes. %s is up to date.\n' "$VERSIONS_FILE"
else
	printf '\nUpdated %s\n' "$VERSIONS_FILE"
fi
