#!/bin/bash
set -euo pipefail

# Refresh managed image digests, then pin the agent CLI versions those images
# carry so the local dev image rebuild actually reinstalls them.
#
# `agentbox bump` only repins digests in the managed compose layers. This repo
# overrides the agent image with a locally built agent-sandbox-dev:<agent>, so
# those digests are never pulled at run time. The versions the bumped images
# were built with are still the right thing to build locally, and they are
# recorded as image labels, so read them back and write them to the versions
# file that build-dev-image.bash applies.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
COMPOSE_DIR="${COMPOSE_DIR:-$REPO_ROOT/.agent-sandbox/compose}"
METADATA_FILE="${METADATA_FILE:-$REPO_ROOT/.agent-sandbox/active-target.env}"
VERSIONS_FILE="${VERSIONS_FILE:-$SCRIPT_DIR/dev-image-versions.env}"

SUPPORTED_AGENTS="claude copilot codex gemini factory opencode pi hermes"

# Hermes is pinned by its calver git tag (HERMES_VERSION, recorded in the
# hermes-ref label), but published images also carry the release's semver in
# hermes-version. images/build.sh accepts that as HERMES_SEMVER so the local
# image ends up labelled the same way. The pair only makes sense together, so
# HERMES_SEMVER is written and carried forward with HERMES_VERSION rather than
# treated as an independent pin.
HERMES_SEMVER_LABEL='com.mattolson.agentsandbox.hermes-version'

usage() {
	cat <<'USAGE'
Usage: ./scripts/bump-dev-image.bash

Runs `agentbox bump` to refresh managed image digests, then reads the agent CLI
version label off each newly pinned image and records it in the versions file
consumed by ./scripts/build-dev-image.bash.

Fails, leaving the versions file untouched, if no concrete version could be
read for the agent that `make setup` builds next. Otherwise `make bump` would
rebuild the dev image at a stale pin while reporting success.

Does not rebuild anything. Use `make bump` to bump and then run `make setup`.

Optional environment variables:
  AGENT          Agent that must resolve (default: ACTIVE_AGENT from .agent-sandbox)
  AGENTBOX       agentbox command to run (default: agentbox on PATH,
                 then ./bin/agentbox, then `go run ./cmd/agentbox`)
  COMPOSE_DIR    Managed compose directory (default: ./.agent-sandbox/compose)
  METADATA_FILE  Agent metadata file (default: ./.agent-sandbox/active-target.env)
  VERSIONS_FILE  Output file (default: ./scripts/dev-image-versions.env)
USAGE
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
	usage
	exit 0
fi

# build.sh environment variable that sets this agent's CLI version.
version_var_for() {
	case "$1" in
		claude) printf 'CLAUDE_CODE_VERSION' ;;
		copilot) printf 'COPILOT_VERSION' ;;
		codex) printf 'CODEX_VERSION' ;;
		gemini) printf 'GEMINI_VERSION' ;;
		factory) printf 'FACTORY_VERSION' ;;
		opencode) printf 'OPENCODE_VERSION' ;;
		pi) printf 'PI_VERSION' ;;
		hermes) printf 'HERMES_VERSION' ;;
		*) return 1 ;;
	esac
}

# Image label holding the value that the above variable expects. Hermes is the
# odd one: HERMES_VERSION is a git tag, which is recorded as hermes-ref, while
# hermes-version holds the derived semver (see HERMES_SEMVER_LABEL).
version_label_for() {
	case "$1" in
		claude) printf 'com.mattolson.agentsandbox.claude-code-version' ;;
		copilot) printf 'com.mattolson.agentsandbox.copilot-version' ;;
		codex) printf 'com.mattolson.agentsandbox.codex-version' ;;
		gemini) printf 'com.mattolson.agentsandbox.gemini-version' ;;
		factory) printf 'com.mattolson.agentsandbox.factory-version' ;;
		opencode) printf 'com.mattolson.agentsandbox.opencode-version' ;;
		pi) printf 'com.mattolson.agentsandbox.pi-version' ;;
		hermes) printf 'com.mattolson.agentsandbox.hermes-ref' ;;
		*) return 1 ;;
	esac
}

# Mirrors docker.IsLocalImageRef in internal/docker/images.go.
is_local_image() {
	case "$1" in
		*:local) return 0 ;;
		*/*) return 1 ;;
		*) return 0 ;;
	esac
}

# Reads the `image:` value from the `agent` service of a managed compose layer.
# These files are generated by internal/scaffold, so the indentation is stable.
read_agent_image() {
	awk '
		/^[[:space:]]*services:[[:space:]]*$/ { in_services = 1; next }
		in_services && /^  [A-Za-z0-9_.-]+:[[:space:]]*$/ {
			svc = $0
			sub(/^  /, "", svc)
			sub(/:[[:space:]]*$/, "", svc)
			next
		}
		svc == "agent" && /^    image:[[:space:]]*/ {
			sub(/^    image:[[:space:]]*/, "")
			print
			exit
		}
	' "$1"
}

# Prints the trimmed value of a version label on a local image. Explains on
# stderr and returns 1 when the label is missing, "latest", or unsafe to write
# into a KEY=value file or pass to build.sh.
read_version_label() {
	# $1 = agent, $2 = image, $3 = label
	local value
	value="$(docker image inspect --format "{{ index .Config.Labels \"$3\" }}" "$2" 2>/dev/null || printf '')"
	value="$(printf '%s' "$value" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

	case "$value" in
		# `index` on a missing key renders as "<no value>".
		'' | '<no value>')
			printf '  %s: no %s label on %s\n' "$1" "$3" "$2" >&2
			return 1
			;;
		latest)
			printf '  %s: %s is "latest", so the image carries no concrete version\n' "$1" "$3" >&2
			return 1
			;;
		# Anything else that would be unsafe in a KEY=value file or build arg.
		*[!A-Za-z0-9._+-]*)
			printf '  %s: unexpected %s label value "%s"\n' "$1" "$3" "$value" >&2
			return 1
			;;
	esac

	printf '%s' "$value"
}

read_pinned_version() {
	# $1 = variable name
	[ -f "$VERSIONS_FILE" ] || return 0
	sed -n "s/^$1=//p" "$VERSIONS_FILE" | tail -1
}

read_resolved_version() {
	# $1 = variable name
	awk -v k="$1" '$1 == k { print $2; exit }' "$RESOLVED_FILE"
}

report_change() {
	# $1 = variable name, $2 = previous value, $3 = new value
	if [ -n "$2" ] && [ -n "$3" ]; then
		printf '  %s: %s -> %s\n' "$1" "$2" "$3"
	elif [ -n "$3" ]; then
		printf '  %s: pinned to %s\n' "$1" "$3"
	else
		printf '  %s: dropped (was %s)\n' "$1" "$2"
	fi
}

if ! command -v docker >/dev/null 2>&1; then
	printf 'docker is required to read version labels from bumped images\n' >&2
	exit 1
fi

if [ ! -d "$COMPOSE_DIR" ]; then
	printf 'Managed compose directory not found: %s\nRun `agentbox init` first.\n' "$COMPOSE_DIR" >&2
	exit 1
fi

# The agent `make setup` builds next, resolved the same way build-dev-image.bash
# does. Its version must resolve for the bump to count as a success.
ACTIVE_AGENT=""
if [ -f "$METADATA_FILE" ]; then
	# shellcheck disable=SC1090
	. "$METADATA_FILE"
	ACTIVE_AGENT="${ACTIVE_AGENT:-}"
fi
TARGET_AGENT="${AGENT:-$ACTIVE_AGENT}"
if [ -n "$TARGET_AGENT" ] && ! version_var_for "$TARGET_AGENT" >/dev/null; then
	printf 'Unsupported agent for local dev image: %s\n' "$TARGET_AGENT" >&2
	exit 1
fi

cd "$REPO_ROOT"

AGENTBOX_CMD=()
if [ -n "${AGENTBOX:-}" ]; then
	# Word splitting is intentional so AGENTBOX can carry arguments.
	# shellcheck disable=SC2206
	AGENTBOX_CMD=($AGENTBOX)
elif command -v agentbox >/dev/null 2>&1; then
	AGENTBOX_CMD=(agentbox)
elif [ -x "$REPO_ROOT/bin/agentbox" ]; then
	AGENTBOX_CMD=("$REPO_ROOT/bin/agentbox")
elif command -v go >/dev/null 2>&1; then
	AGENTBOX_CMD=(go run ./cmd/agentbox)
else
	printf 'Unable to locate agentbox. Install it, run `make build`, or set AGENTBOX.\n' >&2
	exit 1
fi

printf 'Running %s bump\n' "${AGENTBOX_CMD[*]}"
"${AGENTBOX_CMD[@]}" bump

printf '\nReading agent CLI versions from bumped images\n'

# Lines of "VARIABLE value" for everything read off the images this run.
RESOLVED_FILE="$(mktemp)"
trap 'rm -f "$RESOLVED_FILE"' EXIT

for agent in $SUPPORTED_AGENTS; do
	layer="$COMPOSE_DIR/agent.$agent.yml"
	[ -f "$layer" ] || continue

	image="$(read_agent_image "$layer")"
	if [ -z "$image" ]; then
		printf '  %s: no agent image in %s, skipping\n' "$agent" "$layer" >&2
		continue
	fi

	if is_local_image "$image"; then
		printf '  %s: %s is a local image, skipping\n' "$agent" "$image" >&2
		continue
	fi

	# `agentbox bump` keeps the old digest when its pull fails, and that image
	# may never have been pulled here at all.
	if ! docker image inspect "$image" >/dev/null 2>&1; then
		printf '  %s: %s is not present locally (pull failed?), skipping\n' "$agent" "$image" >&2
		continue
	fi

	version="$(read_version_label "$agent" "$image" "$(version_label_for "$agent")")" || continue
	printf '  %s: %s\n' "$agent" "$version"
	printf '%s %s\n' "$(version_var_for "$agent")" "$version" >> "$RESOLVED_FILE"

	# Optional companion pin. Without it build.sh labels the local image with
	# the tag, which is what a bare HERMES_VERSION=<tag> build does anyway.
	if [ "$agent" = hermes ]; then
		if semver="$(read_version_label "$agent" "$image" "$HERMES_SEMVER_LABEL")"; then
			printf '  %s: semver %s\n' "$agent" "$semver"
			printf 'HERMES_SEMVER %s\n' "$semver" >> "$RESOLVED_FILE"
		fi
	fi
done

if [ ! -s "$RESOLVED_FILE" ]; then
	printf '\nNo agent versions resolved. Leaving %s unchanged.\n' "$VERSIONS_FILE" >&2
	exit 1
fi

if [ -n "$TARGET_AGENT" ]; then
	target_var="$(version_var_for "$TARGET_AGENT")"
	if [ -z "$(read_resolved_version "$target_var")" ]; then
		current="$(read_pinned_version "$target_var")"
		printf '\nNo version resolved for %s, which `make setup` builds next.\n' "$TARGET_AGENT" >&2
		printf 'Leaving %s unchanged rather than rebuilding it at %s.\n' "$VERSIONS_FILE" "${current:-latest}" >&2
		printf 'To build a specific version instead: %s=<version> make setup\n' "$target_var" >&2
		exit 1
	fi
fi

TMP_VERSIONS="$(mktemp)"
trap 'rm -f "$RESOLVED_FILE" "$TMP_VERSIONS"' EXIT

cat <<'HEADER' > "$TMP_VERSIONS"
# Agent CLI versions pinned for the local dev image.
#
# Generated by ./scripts/bump-dev-image.bash (via `make bump`) and read by
# ./scripts/build-dev-image.bash (via `make setup`).
#
# Each entry is applied as a default: an explicit environment variable always
# wins, so `CLAUDE_CODE_VERSION=2.1.100 make setup` still overrides a pin here.
#
# Pinning matters because images/build.sh defaults these to "latest", which is a
# cache-stable build arg. Docker reuses the cached install layer and the agent
# CLI never gets reinstalled. A concrete version busts the cache.
#
# HERMES_VERSION is the calver git tag that is built. HERMES_SEMVER is the same
# release's semver, read off the published image so the local image carries the
# matching hermes-version label. It only applies alongside the HERMES_VERSION it
# was recorded with; an explicit HERMES_VERSION ignores it.
HEADER

changed=0
for agent in $SUPPORTED_AGENTS; do
	var="$(version_var_for "$agent")"
	previous="$(read_pinned_version "$var")"
	version="$(read_resolved_version "$var")"
	resolved=1

	# Carry forward pins for agents that were not resolved this run.
	if [ -z "$version" ]; then
		version="$previous"
		resolved=0
	elif [ "$version" != "$previous" ]; then
		changed=1
		report_change "$var" "$previous" "$version"
	fi

	[ -n "$version" ] || continue
	printf '%s=%s\n' "$var" "$version" >> "$TMP_VERSIONS"

	# HERMES_SEMVER travels with HERMES_VERSION: carried forward with it, or
	# replaced by (or dropped with) whatever this run read off the image.
	if [ "$agent" = hermes ]; then
		previous_semver="$(read_pinned_version HERMES_SEMVER)"
		if [ "$resolved" -eq 1 ]; then
			semver="$(read_resolved_version HERMES_SEMVER)"
		else
			semver="$previous_semver"
		fi
		if [ "$semver" != "$previous_semver" ]; then
			changed=1
			report_change HERMES_SEMVER "$previous_semver" "$semver"
		fi
		[ -n "$semver" ] || continue
		printf 'HERMES_SEMVER=%s\n' "$semver" >> "$TMP_VERSIONS"
	fi
done

mv "$TMP_VERSIONS" "$VERSIONS_FILE"
trap 'rm -f "$RESOLVED_FILE"' EXIT

if [ "$changed" -eq 0 ]; then
	printf '\nNo version changes. %s is up to date.\n' "$VERSIONS_FILE"
else
	printf '\nUpdated %s\n' "$VERSIONS_FILE"
fi
